name: Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Ensure this is set if you are using Azure login with id-token

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies for backend
      run: |
        cd backend
        npm install
        pip install -r database/requirements.txt

    - name: List files in backend directory for debugging
      run: |
        cd backend
        ls -la  # List files to verify the presence of `.env.production`

    - name: Copy production environment variables
      run: |
        cd backend
        cp .env.production .env  # Copy the environment file
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-oidc: true  # 启用OIDC身份验证

    - name: Start Node.js server
      run: |
        cd backend
        nohup node server.js &  # 使用 nohup 和 & 启动 Node.js 服务器并将其放在后台运行

    - name: Run Python script
      run: |
        cd database
        python signup_db.py

    - name: Build and Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'yvweb-backend'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './backend'