name: Frontend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Ensure this is set if you are using Azure login with id-token

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies for frontend
      run: |
        cd frontend
        npm install

    - name: Copy production environment variables and config
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        cp frontend/.env.production frontend/.env
        cp frontend/src/config.production.json frontend/src/config.json

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-oidc: true  # Enable OIDC authentication if required

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Deploy to Azure Web App frontend
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'yvweb-frontend'
        slot-name: 'production'
        package: './frontend/build'
