name: Python Script Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-python:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Ensure this is set if you are using Azure login with id-token

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies for Python
      run: |
        cd backend/database
        pip install -r requirements.txt

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-oidc: true  # Enable OIDC authentication if required

    - name: Run Python script
      run: |
        cd backend/database
        python signup_db.py
